# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
class:
  short: SAVI-800
  long: Advanced Interactive Web Mapping
  term: Spring 2016
school:
  name: Pratt SAVI
  link: https://www.pratt.edu/pratt-research-and-centers/spatial-analysis-visualization-initiative/
email:
description: > # this means to ignore newlines until "baseurl:"
  DESCRIPTION
baseurl: "" # the subpath of your site, e.g. /blog
url: http://pratt-savi.github.io/savi800-spring2016/
twitter_username: PrattSAVI
github_username: pratt-savi

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    author: name
    output: true
    permalink: /projects/:path/
